name: Bananas Push Image

on:
  workflow_call:
    inputs:
      commit_sha:
        description: 'Commit SHA to use as the image tag'
        required: true
        type: string
      github_environment:
        description: 'GitHub environment to publish to'
        required: true
        type: string

jobs:
  push_image:
    uses: ./.github/workflows/ecr_push.yaml
    with:
      commit_sha: ${{ inputs.commit_sha }}
      github_environment: ${{ inputs.github_environment }}
      aws_iam_role_arn: ${{ vars.AWS_IAM_ROLE_ARN_BANANAS_DEPLOY }}
      aws_region: ${{ vars.AWS_IAM_REGION_BANANAS_DEPLOY }}
      ecr_repository: ${{ vars.AWS_ECR_REPOSITORY_BANANAS }}
      build_context: bananas/

  output_image_tag:
    runs-on: ubuntu-24.04
    needs: push_image
    steps:
      - name: Output image tag
        run: echo "Pushed image tag: ${{ needs.push_image.outputs.image_tag }}"
