name: Bananas CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/rails_ci.yml
    with:
      working_directory: bananas

  push_image:
    needs: ci
    uses: ./.github/workflows/ecr_push.yaml
    with:
      commit_sha: ${{ github.sha }}
      github_environment: bananas-ecr-push
      aws_iam_role_arn: ${{ vars.AWS_IAM_ROLE_ARN_BANANAS_DEPLOY }}
      aws_region: ${{ vars.AWS_IAM_REGION_BANANAS_DEPLOY }}
      ecr_repository: ${{ vars.AWS_ECR_REPOSITORY_BANANAS }}
      build_context: bananas/

  output_image_tag:
    runs-on: ubuntu-24.04
    needs: push_image
    steps:
      - name: Output image tag
        run: |
          echo "Pushed image tag: ${{ needs.push_image.outputs.image_tag }}"
