name: Bananas CI

on:
  pull_request:
  push:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/rails_ci.yml
    with:
      working_directory: bananas
