name: Terraform Plan

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      github_environment:
        description: 'GitHub environment to deploy to'
        required: true
        type: string
      iam_role_duration_seconds:
        description: 'IAM role expiry in seconds'
        required: false
        default: 3600
        type: number
      runner:
        description: 'GitHub runner'
        required: false
        default: 'ubuntu-24.04'
        type: string
      terraform_plan_file_s3_prefix:
        description: 'S3 key prefix for Terraform plan file'
        required: true
        type: string
      terraform_plan_id:
        description: 'ID of the Terraform plan file, usually GITHUB_RUN_ID'
        required: true
        type: string
      terraform_version_file:
        description: 'Path to Terraform file in JSON format containing the `terraform` keyword with `required_version`'
        required: true
        type: string

jobs:
  plan:
    runs-on: ${{inputs.runner}}
    timeout-minutes: 30

    environment: ${{ inputs.github_environment }}

    steps:
      - uses: actions/checkout@v6

      - name: Read Terraform version
        id: terraform_version
        run: echo "TERRAFORM_VERSION=$(cat ${{ inputs.terraform_version_file }} | jq -r .terraform.required_version)" >> $GITHUB_OUTPUT

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ steps.terraform_version.outputs.TERRAFORM_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_IAM_ROLE_TERRAFORM_APPLY }}
          aws-region: ${{ vars.AWS_REGION_TERRAFORM_APPLY }}
          role-duration-seconds: ${{ inputs.iam_role_duration_seconds }}

      - name: make plan
        working-directory: ${{ github.workspace }}

        env:
          # set defined by GitHub repostiory environment
          TF_BACKEND_BUCKET: ${{ vars.TF_BACKEND_BUCKET }}
          TF_BACKEND_REGION: ${{ vars.TF_BACKEND_REGION }}
          TF_BACKEND_ROLE_ARN: ${{ vars.TF_BACKEND_ROLE_ARN }}
          TF_BACKEND_KEY: ${{ vars.TF_BACKEND_KEY }}
        run: |
          set -euo pipefail
          ENVIRONMENT=${{ inputs.environment }} make -f "${{ github.workspace }}/terraform/Makefile" plan_write_file

      - name: Upload Terraform plan file to S3
        working-directory: ${{ github.workspace }}
        run: |
          aws s3 cp ./local.tfplan ${{ inputs.terraform_plan_file_s3_prefix }}/${{ github.event.repository.name }}/${{ inputs.environment }}/${{ inputs.terraform_plan_id }}.tfplan
